import type { Metadata } from "next";
// import font from "next/font/google";
import { Libre_Baskerville } from "next/font/google";
import "./globals.css";
const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-libre-baskerville",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={libreBaskerville.className}
      >
        {children}
      </body>
    </html>
  );
}
